### ISSUE TITLE
failure in storage run

### ISSUE THREAD

**Issue by georgettica** [openshift/osde2e#920]
as seen https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-prod-aws-e2e-next/1455052025380212736

the pvc's are deleted before the pod is, which causes the delete pod to fail with a timeout (as the pod won't be able to run)

https://github.com/openshift/osde2e/blob/e12a5a3c16f37253a96fb3743beb4d3199bce703/pkg/e2e/verify/storage.go#L72

**Comment by mrbarge** [comment]
From the linked job, it would seem that it is actually failing when trying to create the pod rather than when it's trying to delete it, given that it is [this failing assertion](https://github.com/openshift/osde2e/blob/e12a5a3c16f37253a96fb3743beb4d3199bce703/pkg/e2e/verify/storage.go#L69) that ultimately fails the test.

As for why the pod didn't start up, I've checked the must-gather for that job and the pod doesn't successfully run because the volume for the PVC it depends on (in this case, `vol-077e52ff86752cb56`) never successfully attaches to the node it's meant to attach to. Unfortunately the `aws-ebs-csi-driver-controller` logs don't provide any further detail, other than to note:

```
Could not attach volume "vol-077e52ff86752cb56" to node "i-0b61385ed565c7de0": attachment of disk "vol-077e52ff86752cb56" failed, expected device to be attached but was attaching
```

Probably the next step here normally would be to check out the node's logs but we don't have those sadly.

If we see this again, and it's consistently related to the `gp2-csi` storageclass, then that might hone in where we need to look.

**Comment by georgettica** [comment]
thanks for helping me dig deeper into this!
