### ISSUE TITLE
compile time error in nodelabels.go, publishingstrategies_cr.go

### ISSUE THREAD

**Issue by georgettica** [openshift/osde2e#921]
```
You may only call It from within a Describe, Context or When
```

this seems to be fine when looking at the code, but shows this was not tested locally

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-prod-aws-e2e-upgrade-to-latest/1454870829660639232
https://github.com/openshift/osde2e/blob/e12a5a3c16f37253a96fb3743beb4d3199bce703/pkg/e2e/osd/nodelabels.go#L25

---
similar issue in
https://github.com/openshift/osde2e/blob/e12a5a3c16f37253a96fb3743beb4d3199bce703/pkg/e2e/operators/cloudingress/publishingstrategies_cr.go#L21
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/osde2e-prod-aws-e2e-upgrade-rescheduled/1454991614320578560
though here it shows as flakey

**Comment by mrbarge** [comment]
My current suspicion of why this is happening is it might be potentially related to:

- https://github.com/onsi/ginkgo/issues/485 
- https://github.com/onsi/ginkgo/issues/704

If ginkgo's `RunSpecs()` is called twice then it can lead odd and unpredictable behaviour in the results. This would potentially explain why it's a bit random.

As best I can tell osde2e currently does call it twice, once pre-upgrade and once post-upgrade. Seems to be failing in the second post-upgrade invocation. We do consistently see this across various jobs, with varying tests, and the unifying factor is that they're upgrade-related jobs which lends some credence to the aforementioned theory.

**Comment by georgettica** [comment]
this might be solved by adding a channel of `pre-upgrade` tests complete before the `post-upgrade` ones run?

these issues seems to make sense if this premise is correct, now we need to decide on how to make this go away?

**Comment by mrbarge** [comment]
A potential - although high-effort-investment - option is that ginkgo v2 supports the ability to [repeat test suites](https://github.com/onsi/ginkgo/blob/ver2/docs/NEW_INDEX.md#repeating-test-runs-and-managing-flaky-specs). It will offer this via the ginkgo CLI with a `-repeat` option, but would need some doing to engineer inside OSDE2E.

However, this would require first migrating to ginkgo v2, which is problematic because among the various things deprecated in v2 includes running test suites with [custom reporters](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters), which OSDE2E uses, so that aspect would need to be reworked too.
